services:
  build_app:
    build:
      context: .
      dockerfile: ../dockerfiles/maven_step.Dockerfile
    volumes:
      - ../../src/:/../source/src/
      - ../../pom.xml:/../source/pom/pom.xml
      - dependencies:/root/.m2
      - output:/../source/output
  
  serve_app:
    image: amazoncorretto:17.0.14-alpine3.21
    container_name: my-ecommerce
    ports:
      - "8282:8282"
    restart: always
    volumes:
      - output:/home/output/
    depends_on:
      build_app:
        condition: service_completed_successfully
      db:
        condition: service_started
    command: ["sh", "-c", " mkdir -p /home/app ; rm -rf /home/app/*.jar ; cp /home/output/*.jar /home/app/my-ecommerce.jar ; cd /home/app ; java -Dserver.port=8282 -jar my-ecommerce.jar"]
  
  db:
    imge: postgres:17.4-bookworm
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
      POSTGRES_DB: my-ecommerce
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root", "-d", "my-ecommerce"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    

volumes:
  dependencies:
  output: 
  db_data:






